# cloudbuild_app.yaml

steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/mev-fyi/llama-flask-app:$SHORT_SHA'
      - '-f'
      - './Dockerfile_app'
      - '.'

  # 2. Push the image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/mev-fyi/llama-flask-app:$SHORT_SHA'

  # 3. Deploy the new image to your Compute Engine VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instances update-container my-vm-name \
          --zone=europe-west1-b \
          --container-image=gcr.io/mev-fyi/llama-flask-app:$SHORT_SHA \
          --container-restart-policy=always \
          --project=mev-fyi

images:
  - 'gcr.io/mev-fyi/llama-flask-app:$SHORT_SHA'
