steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/mev-fyi/llama-eval-app:$SHORT_SHA'
      - '-f'  # Specify the Dockerfile path
      - './Dockerfile_app'  # Use the path to your Dockerfile
      - './src/Llama_index_sandbox'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mev-fyi/llama-flask-app:$SHORT_SHA']