# Use an official lightweight Python image.
FROM python:3.10

# Set the working directory in the container.
WORKDIR /app

# Install any system dependencies.
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Copy the requirements file and install Python dependencies.
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application source code to the container.
COPY src /app/src

# Set PYTHONPATH to include the directory where your app is located.
ENV PYTHONPATH "${PYTHONPATH}:/app/src"

# Run the Twitter bot application.
CMD ["python", "/app/src/Llama_index_sandbox/twitter_bot_app.py"]
