# Use an official lightweight Python image
FROM python:3.9-slim

# Use a build argument to specify the context
ARG DOCKERIGNORE_CONTEXT=app

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the working directory in the container
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy only the relevant directory to the working directory
COPY . .

# Use the build argument to copy the correct .dockerignore file before the build
COPY .dockerignore.${DOCKERIGNORE_CONTEXT} ./.dockerignore

# Append src directory to PYTHONPATH
ENV PYTHONPATH "${PYTHONPATH}:/app/src"

# Set the Flask environment to production
ENV FLASK_ENV=production

# Set the Flask app to the correct file
ENV FLASK_APP=src/Llama_index_sandbox/app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8080

# Expose the port the app runs on
EXPOSE 8080

# Command to run the application
CMD ["gunicorn", "-b", "0.0.0.0:8080", "src.Llama_index_sandbox.app:app"]
